### ISSUE TITLE
Make the home page component grid dynamic

### ISSUE THREAD

**Issue by dustin-jw** [sparkbox/accessible-components#140]
We’re currently using grid-template-areas with hard-coded names corresponding to the components that we’re showing on the home page. Using CSS and JS similar to how we implemented the masonry layout, we can change our approach and get row/column start/end numbers from Airtable.

First, we’ll need to set up the grid. Note: assume that these styles only apply at a breakpoint large enough to show multiple columns.

```scss
.components-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  
  &__item {
    --row-start: auto;
    --row-span: 1;
    --column-start: auto;
    --column-span: 1;
    
    grid-row: var(--row-start, auto) / span var(--number-of-rows, 1);
    grid-column: var(--column-start, auto) / span var(--number-of-columns, 1);
  }
}
```

Then, in Airtable, we can use new columns to specify these values:

- Row Start
- Row Span
- Column Start
- Column Span

We will also need to update index.page.jsx to use getStaticProps to read those values from Airtable.

Then we can use those values to set the CSS variables in style attributes, again similar to what we’re doing for the masonry layout.

Since our data would be dynamic, and coming from Airtable, the image paths would need to come from Airtable as well.

Definition of Done:

The hard-coded component grid is updated to accept data from Airtable that is used to build out the grid, making it easier to add new components.
